allow-expect-in-tests = true
allow-unwrap-in-tests = true
await-holding-invalid-types = [
    "tokio::sync::MutexGuard",
    "tokio::sync::RwLockReadGuard",
    "tokio::sync::RwLockWriteGuard",
]
disallowed-methods = []

# Increase the size threshold for result_large_err to accommodate
# richer error variants.
large-error-threshold = 256
